### ISSUE TITLE
error: "Unknown or uninitialised column: 'Gene'."

### ISSUE THREAD

**Issue by MerRome** [kieranrcampbell/ouija#8] opened 2019-01-30 10:19 UTC
Hello,
thanks for developing this tool! I am very eager to try it out.

I am having the problem that it seem like I am "loosing" the gene information in the ouija fit, but calling ouija works in priniple.
 
I am working on a sce, where I still see my gene names I am subsetting for:

`SCEsmart[smart.top[1:10],]`
class: SingleCellExperiment 
dim: 10 94 
metadata(1): log.exprs.offset
assays(2): counts logcounts
rownames(10): Jam2 Lgals3 ... Tcl1 Cthrc1
rowData names(12): ENSEMBL SYMBOL ... log10_total_counts AveCount
colnames(94): X00h_01_S24947 X00h_02_S24948 ... X48h_33_S25022 X48h_34_S25023
colData names(39): cellID timepoint ... pct_counts_in_top_500_features_Mito phases
reducedDimNames(0):
spikeNames(0):

`options(mc.cores = parallel::detectCores())`
`oui <- ouija(SCEsmart[smart.top[1:10],],`
 `single_cell_experiment_assay = "logcounts" ,`
         ` inference_type = "hmc")  `

`print(oui)`
A Ouija fit with 94 cells and 10 marker genes 
Inference type:  Hamiltonian Monte Carlo 
MCMC info: 10000 iterations on 1 chains 
(Gene behaviour) Switch/transient: 10 / 0

`plot_expression(oui)`
![expression](https://user-images.githubusercontent.com/38718729/51973867-e9e3a400-247e-11e9-90fd-04a37da148bf.jpeg)

so here I do not see the genenames anymore. Any downstream analysis produces errors like:

`plot_switch_times(oui)`
Unknown or uninitialised column: 'Gene'.Unknown or uninitialised column: 'Gene'.
Error in `$<-.data.frame`(`*tmp*`, "Gene", value = integer(0)) : replacement has 0 rows, data has 10

`gene_regs <- gene_regulation(oui)`
Error: All columns in a tibble must be 1d or 2d objects: * Column `gene_i` is NULL * Column `gene_j` is NULL Call `rlang::last_error()` to see a backtrace

I have to confess that my understanding of the under laying data structure is limited. Do you have any suggestions what could cause this behaviour and how I could fix it?

Thank you for any help!
Best,
Merrit

**Comment by kieranrcampbell** [comment] 2019-01-30 12:49
Hi @MerRome 

Thanks for your email. I suspect this is due to various upstream `tibble` changes that have recently happened. Would you be able to email (gmail: kieranrcampbell) me your reduced SingleCellExperiment `SCEsmart[smart.top[1:10],]`  and I'll try to fix the problem? 

Thanks

Kieran

**Comment by kieranrcampbell** [comment] 2019-02-05 01:45
Hi @MerRome 

Thanks for sending over your SCE.

I updated all my packages and was able to reproduce your error. I think the issue was `SummarizedExperiments` not retaining gene names as columns. This should be fixed in d98fa96e61315de5700281d1443a263473a30c07.

Can you re- `install_github` and let me know if there are further problems? I can now make the necessary plots such as 

![image](https://user-images.githubusercontent.com/2039489/52248679-6a057180-28a4-11e9-9a80-8567574a798e.png)
and
![image](https://user-images.githubusercontent.com/2039489/52248690-738ed980-28a4-11e9-9f8a-6ed0b0864c51.png)

**Comment by MerRome** [comment] 2019-02-05 09:11
Dear Kieran,
yes, everything works fine now.
Thank you for your help!
Best,
Merrit

**Closed as completed** 2019-02-05 10:25 UTC
